version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hokohealthdc"
s3_bucket = "hoko-healthdc-stg"
s3_prefix = "sourcecode"
region = "ap-northeast-1"
profile = "infodeliver-test"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
